# .github/workflows/main.yml

name: Daily Gamma Report

on:
  # Schedule to run at multiple times (Monday-Friday only)
  schedule:
    # --- For the 12:00 PM (Noon) Sweden Time Report ---
    # Runs at 10:00 UTC (12:00 CEST) during summer months (Apr-Oct), Mon-Fri only
    - cron: '0 10 * 4-10 1-5'
    # Runs at 11:00 UTC (12:00 CET) during winter months (Nov-Mar), Mon-Fri only
    - cron: '0 11 * 1-3,11-12 1-5'
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-email-report:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Gamma Reporter for SPX
      env:
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
        EMAIL_APP_PASSWORD: ${{ secrets.EMAIL_APP_PASSWORD }}
      run: python gamma_reporter.py SPX
