# .github/workflows/main.yml

name: Daily Gamma Report

on:
  # Schedule to run every day at 12:00 UTC (adjust as needed)
  schedule:
    - cron: '0 12 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-email-report:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Gamma Reporter for SPX
      env:
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
        EMAIL_APP_PASSWORD: ${{ secrets.EMAIL_APP_PASSWORD }}
      run: python gamma_reporter.py SPX
      
    # Optional: Add another step to run for another index like NDX
    # - name: Run Gamma Reporter for NDX
    #   env:
    #     SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
    #     RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
    #     EMAIL_APP_PASSWORD: ${{ secrets.EMAIL_APP_PASSWORD }}
    #   run: python gamma_reporter.py NDX
